# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-30 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=36)),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_time', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('last_scraped', models.DateTimeField(null=True)),
                ('normalized', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.NormalizedSong')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('timezone', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('last_scraped', models.DateTimeField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Song'),
        ),
        migrations.AddField(
            model_name='play',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Station'),
        ),
        migrations.AddField(
            model_name='normalizedsong',
            name='tags',
            field=models.ManyToManyField(to='scraper.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('artist', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='play',
            unique_together=set([('time', 'station')]),
        ),
        migrations.AlterUniqueTogether(
            name='normalizedsong',
            unique_together=set([('mbid', 'artist', 'title')]),
        ),
    ]
