name: Main Pipeline
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 2 1 * *'
jobs:
  radiostats:
    name: Scrape
    runs-on: ubuntu-latest
    container:
      image: python:2.7
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: pip install -r requirements.txt
      - name: Download database
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          name: database
          branch: master
      - name: Scrape
        run: python manage.py scrape --sequential
      - name: Normalize
        run: python manage.py normalize
      - name: Archive dataset
        uses: actions/upload-artifact@v4
        with:
          name: database
          path: radiostats/db.sqlite3